services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200
    depends_on:
      - api-gateway
      - cart-service
      - product-service
      - category-service

  api-gateway:
    image: mathiskrr/breizhsport-api-gateway:latest
    ports:
      - 3000:3000
    environment:
      NODE_ENV: test

  cart-service:
    image: mathiskrr/breizhsport-cart:latest
    ports:
      - 4001:4001
    environment:
      NODE_ENV: test

  product-service:
    image: mathiskrr/breizhsport-product:latest
    ports:
      - 4002:4002
    environment:
      NODE_ENV: test

  category-service:
    image: mathiskrr/breizhsport-category:latest
    ports:
      - 4003:4003
    environment:
      NODE_ENV: test
