services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200
    depends_on:
      - api-gateway
      - cart-service
      - product-service
      - category-service

  api-gateway:
    image: mathiskrr/breizhsport-api-gateway:develop
    ports:
      - 3000:3000
    environment:
      NODE_ENV: test
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_DIALECT: ${DB_DIALECT}

  cart-service:
    image: mathiskrr/breizhsport-cart:develop
    ports:
      - 4001:4001
    environment:
      NODE_ENV: test
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_DIALECT: ${DB_DIALECT}

  product-service:
    image: mathiskrr/breizhsport-product:develop
    ports:
      - 4002:4002
    environment:
      NODE_ENV: test
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_DIALECT: ${DB_DIALECT}

  category-service:
    image: mathiskrr/breizhsport-category:develop
    ports:
      - 4003:4003
    environment:
      NODE_ENV: test
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_DIALECT: ${DB_DIALECT}
