services:
  server:
    image: mathiskrr/breizhsport-front:develop
    environment:
      NODE_ENV: production
    ports:
      - "4200:4200"
    depends_on:
      - api-gateway
      - cart-service
      - product-service
      - category-service


  api-gateway:
    image: mathiskrr/breizhsport-api-gateway:develop
    ports:
      - 3000:3000
    environment:
      NODE_ENV: test
      PORT: 3000
    env_file: .env

  cart-service:
    image: mathiskrr/breizhsport-cart:develop
    ports:
      - 4001:4001
    environment:
      NODE_ENV: test
      PORT: 4001
    env_file: .env

  product-service:
    image: mathiskrr/breizhsport-product:develop
    ports:
      - 4002:4002
    environment:
      NODE_ENV: test
      PORT: 4002
    env_file: .env

  category-service:
    image: mathiskrr/breizhsport-category:develop
    ports:
      - 4003:4003
    environment:
      NODE_ENV: test
      PORT: 4003
    env_file: .env