name: Cypress Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  cypress-tests:
    runs-on: ubuntu-22.04
    steps:
      # Étape 1 : Checkout du code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Étape 2 : Configuration de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      # Étape 3 : Nettoyer node_modules et package-lock.json
      - name: Clean Node Modules
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      # Étape 4 : Créer le dossier videos dans le bon emplacement
      - name: Create videos directory
        run: mkdir -p breizhsport-front/cypress/videos

      # Étape 5 : Installation des dépendances
      - name: Install Dependencies
        run: npm install

      # Étape 6 : Installation de Cypress (sans exécution des tests)
      - name: Cypress E2E Install
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          working-directory: breizhsport-front

      # Étape 7 : Démarrer le serveur Angular en arrière-plan
      - name: Start Angular Server
        run: npx ng serve &
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      # Étape 8 : Exécuter les tests Cypress
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          working-directory: breizhsport-front
          # wait-on: "http://localhost:4200"

      # Étape 9 : Vérifier si les artefacts existent.
      - name: Check if artifacts exist
        id: check-artifacts
        run: |
          if [ -d "breizhsport-front/cypress/videos" ] || [ -d "breizhsport-front/cypress/screenshots" ]; then
            echo "artifacts_exist=true" >> $GITHUB_OUTPUT
          else
            echo "artifacts_exist=false" >> $GITHUB_OUTPUT
          fi

      # Étape 10 : Téléverser les artefacts (vidéos, screenshots, etc.)
      - name: Upload Cypress Artifacts
        if: always() && steps.check-artifacts.outputs.artifacts_exist == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            breizhsport-front/cypress/videos
            breizhsport-front/cypress/screenshots
          retention-days: 3
  publish-on-docker:
    needs: [cypress-tests]
    if: github.ref == 'refs/heads/main'
    uses: Breizhsport-2025-cube-3/breizhsport-infra/.github/workflows/publish_on_docker.yml@main
    secrets:
      tags: ${{ secrets.DOCKER_USERNAME }}/breizhsport-front:develop
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PAT: ${{ secrets.DOCKER_PAT }}

      