name: Cypress Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  cypress-tests:
    runs-on: ubuntu-22.04
    services:
      server:
        image: mathiskrr/breizhsport-front:develop
        env:
          CATEGORIES_SERVICE_URL: ${{secrets.CATEGORIES_SERVICE_URL}}
          PRODUCT_SERVICE_URL: ${{secrets.PRODUCT_SERVICE_URL}}
          CART_SERVICE_URL: ${{secrets.CART_SERVICE_URL}}
        ports:
          - 4200:4200
      api-gateway:
        image: mathiskrr/breizhsport-api-gateway:develop
        env:
          DB_NAME: ${{secrets.DB_NAME}}
          DB_USER: ${{secrets.DB_USER}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          DB_HOST: ${{secrets.DB_HOST}}
          DB_DIALECT: ${{secrets.DB_DIALECT}}
        ports:
          - 3000:3000
      cart-service:
        image: mathiskrr/breizhsport-cart:develop
        env:
          DB_NAME: ${{secrets.DB_NAME}}
          DB_USER: ${{secrets.DB_USER}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          DB_HOST: ${{secrets.DB_HOST}}
          DB_DIALECT: ${{secrets.DB_DIALECT}}
        ports:
          - 4001:4001
      product-service:
        image: mathiskrr/breizhsport-product:develop
        env:
          DB_NAME: ${{secrets.DB_NAME}}
          DB_USER: ${{secrets.DB_USER}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          DB_HOST: ${{secrets.DB_HOST}}
          DB_DIALECT: ${{secrets.DB_DIALECT}}
        ports:
          - 4002:4002
      categorie-service:
        image: mathiskrr/breizhsport-category:develop
        env:
          DB_NAME: ${{secrets.DB_NAME}}
          DB_USER: ${{secrets.DB_USER}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          DB_HOST: ${{secrets.DB_HOST}}
          DB_DIALECT: ${{secrets.DB_DIALECT}}
        ports:
          - 4003:4003
      
    steps:
      # Étape 1 : Checkout du code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Étape 2 : Créer un fichier .env pour Docker Compose
      - name: Create .env file for Docker Compose
        run: |
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_DIALECT=${{ secrets.DB_DIALECT }}" >> .env

      # Étape 3 : Configurer Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Étape 4 : Vérifier si le frontend fonctionne
      - name: Test if Frontend is Running
        run: curl -I http://localhost:4200 || exit 1

      # Étape 5 : Attendre que l’API Gateway soit prête
      - name: Wait for API Gateway to be ready
        run: npx wait-on http://localhost:3000 --timeout=90000

      # Étape 6 : Vérifier si l’API envoie bien les catégories
      - name: Check API Categories Response
        run: curl -s http://localhost:3000/categories

      # Étape 7 : Vérifier les conteneurs en cours d'exécution
      - name: Check running Docker containers
        run: docker ps

      # Étape 8 : Vérifier les conteneurs arrêtés pour diagnostiquer les erreurs
      - name: Check all Docker containers (including stopped)
        run: docker ps -a

      # Étape 9 : Afficher les logs Docker Compose pour voir les erreurs éventuelles
      - name: Check Docker Compose Logs
        run: docker compose logs

      # Étape 10 : Configuration de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      # Étape 11 : Nettoyer node_modules et package-lock.json
      - name: Clean Node Modules
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      # Étape 12 : Créer le dossier videos pour Cypress
      - name: Create videos directory
        run: mkdir -p breizhsport-front/cypress/videos

      # Étape 13 : Installation des dépendances
      - name: Install Dependencies
        run: npm install --save-dev

      # Étape 14 : Installation de Cypress (sans exécution des tests)
      - name: Cypress E2E Install
        uses: cypress-io/github-action@v6
        with:
          runTests: false

      # Étape 15 : Attendre que le serveur Angular soit prêt
      - name: Wait for Frontend to be ready
        run: npx wait-on http://localhost:4200 --timeout=90000

      # Étape 16 : Exécuter les tests Cypress
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          install: false

      # Étape 17 : Vérifier si les artefacts Cypress existent
      - name: Check if artifacts exist
        id: check-artifacts
        run: |
          if [ -d "breizhsport-front/cypress/videos" ] || [ -d "breizhsport-front/cypress/screenshots" ]; then
            echo "artifacts_exist=true" >> $GITHUB_OUTPUT
          else
            echo "artifacts_exist=false" >> $GITHUB_OUTPUT
          fi

      # Étape 18 : Upload des artefacts Cypress (vidéos, screenshots)
      - name: Upload Cypress Artifacts
        if: always() && steps.check-artifacts.outputs.artifacts_exist == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            breizhsport-front/cypress/videos
            breizhsport-front/cypress/screenshots
          retention-days: 3

      # Étape 19 : Nettoyer les conteneurs après les tests
      - name: Shutdown Docker Containers
        if: always()
        run: docker compose --env-file .env -f compose.yaml down

  publish-on-docker:
    needs: [cypress-tests]
    if: github.ref == 'refs/heads/main'
    uses: Breizhsport-2025-cube-3/breizhsport-infra/.github/workflows/publish_on_docker.yml@main
    secrets:
      tags: ${{ secrets.DOCKER_USERNAME }}/breizhsport-front:develop
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
