name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-22.04 # Utilisez une version spécifique pour éviter l'avertissement
    defaults:
      run:
        working-directory: breizhsport-front
    steps:
      # Étape 1 : Checkout du code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Étape 2 : Configuration de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      # Étape 3 : Nettoyer node_modules et package-lock.json
      - name: Clean Node Modules
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      # Étape 4 : Installation des dépendances
      - name: Install Dependencies
        run: npm install

      # Étape 5 : Installation de Cypress (sans exécution des tests)
      - name: Cypress E2E Install
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          working-directory: breizhsport-front

      # Étape 6 : Démarrer le serveur Angular en arrière-plan
      - name: Start Angular Server
        run: npx ng serve &
        env:
          NODE_OPTIONS: --openssl-legacy-provider # Option pour éviter les erreurs OpenSSL

      # Étape 7 : Exécuter les tests Cypress
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          working-directory: breizhsport-front
          wait-on: "http://localhost:4200" # Attendre que le serveur Angular soit prêt

      # Étape 8 : Vérifier si les artefacts existent
      - name: Check if artifacts exist
        id: check-artifacts
        run: |
          if [ -d "cypress/videos" ] || [ -d "cypress/screenshots" ]; then
            echo "artifacts_exist=true" >> $GITHUB_OUTPUT
          else
            echo "artifacts_exist=false" >> $GITHUB_OUTPUT
          fi

      # Étape 9 : Téléverser les artefacts (vidéos, screenshots, etc.)
      - name: Upload Cypress Artifacts
        if: always() && steps.check-artifacts.outputs.artifacts_exist == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots
          retention-days: 3