name: Integration

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  Backend:
    runs-on: ubuntu-latest

    services:
      api-gateway:
        image: mathiskrr/breizhsport-api-gateway:develop
        ports:
          - 3000:3000
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_DIALECT: ${{ secrets.DB_DIALECT }}
        options: --health-cmd="curl --fail http://localhost:3000 || exit 1" --health-interval=10s --health-timeout=5s --health-retries=5

      cart-service:
        image: mathiskrr/breizhsport-cart:develop
        ports:
          - 4001:4001
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_DIALECT: ${{ secrets.DB_DIALECT }}
        options: --health-cmd="curl --fail http://localhost:4001 || exit 1" --health-interval=10s --health-timeout=5s --health-retries=5

      product-service:
        image: mathiskrr/breizhsport-product:develop
        ports:
          - 4002:4002
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_DIALECT: ${{ secrets.DB_DIALECT }}
        options: --health-cmd="curl --fail http://localhost:4002 || exit 1" --health-interval=10s --health-timeout=5s --health-retries=5

      category-service:
        image: mathiskrr/breizhsport-category:develop
        ports:
          - 4003:4003
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_DIALECT: ${{ secrets.DB_DIALECT }}
        options: --health-cmd="curl --fail http://localhost:4003 || exit 1" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm install

      - name: Run Backend Tests
        run: npm run test

      - name: Upload Backend Test Results
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-results
          path: backend/test-results
          retention-days: 3

  Frontend:
    needs: [Backend]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm install

      - name: Start Frontend for E2E Tests
        run: npx ng serve &
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      - name: Wait for Frontend to be ready
        run: npx wait-on http://localhost:4200 --timeout=60000

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          install: false

      - name: Upload Cypress Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            frontend/cypress/videos
            frontend/cypress/screenshots
          retention-days: 3
