name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Étape 2 : Configuration de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      # Étape 3 : Installation des dépendances
      - name: Install Dependencies
        run: npm install

      # Étape 4 : Exécution des tests Cypress
      - name: Run Cypress Tests
        run: npx cypress run

      # Étape 5 (Optionnelle) : Téléverser les artefacts (vidéos, screenshots, etc.)
      - name: Upload Cypress Artifacts
        if: always() # Téléverse les artefacts même si les tests échouent
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots
          retention-days: 3